version: '3'

services:

  my-app:
    container_name: my-app
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    depends_on:
      - my-app-db
    volumes:
      - .:/app
    command: /start
    ports:
      - "80:8000"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  my-app-db:
    image: postgres:17.5
    container_name: my-app-db
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data:Z
    env_file:
      - .env
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
    ports:
      - ${EXTERNAL_POSTGRES_PORT}:5432
